name: 'transcribe-media'
on:
  issues:
    types:
      - opened
      - edited
  issue_comment:
    types:
      - created
      - edited
  pull_request:
    types:
      - opened
      - edited
  pull_request_review_comment:
    types:
      - created
      - edited
      
jobs:
  transcribe-media:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Looks like set-env is deprecated so we need to use the env variable: $GITHUB_ENV
      - name: set text input pull request
        if: ${{ github.event.pull_request.body }}
        run: |
          echo "pr_body=${ github.event.pull_request.body }" >> $GITHUB_ENV

      - name: set text input issue
        if: ${{ github.event.issue.body }}
        run: |
          echo "issue_body=${ github.event.issue.body }" >> $GITHUB_ENV

      - name: set text input comment
        if: ${{ github.event.comment.body }}
        run: |
          echo "comment_body=${ github.event.comment.body }" >> $GITHUB_ENV

      - uses: ./
        id: transcribe-media
        name: "Run Transcribe Media"
        with:
          azure-cognitive-subscription-key: ${{ secrets.AZURE_COGNITIVE_SUBSCRIPTION_KEY }}
      # - name: Dump output
      #   env:
      #     OUTPUTS: ${{ toJson(steps.transcribe-media.outputs) }}
        # run: echo "$OUTPUTS"